site_name: 西电计科学习指南
site_url: https://lzhms.github.io/XidianCS
repo_name: LZHMS/XidianCS
repo_url: https://github.com/LZHMS/XidianCS
theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: images/favicon.png
  icon:
    logo: material/library
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

copyright: Copyright &copy; 2024 Xidian CS
nav:
  - 主页: 
    - index.md
    - 前言: Home/Introduction.md
  - 计科大类基础课:
    - CSBasic/index.md
    - 思政军体课:
      - 习近平新时代中国特色社会主义思想概论: CSBasic/Politics/XiIdeas.md
    - 通识选修课: CSBasic/General/index.md
    - 数理基础课:
      - 高等数学(I): CSBasic/Maths/AdvancedMath1.md
    - 国际双创课: CSBasic/Internation/index.md
    - 专业基础课:
      - 计算机导论与程序设计: CSBasic/ProfBase/ComputerIntroduction.md
    - 专业核心课:
      - 数据结构: CSBasic/ProfCore/DataStructure.md
  
  - 计科嵌入式系统方向:
    - EmbeddedSystem/index.md
  - 计科软件与理论方向:
    - SoftwareTheory/index.md
  - 计科大数据智能方向:
    - Intelligence/index.md
  - 计科网络与信息安全方向:
    - Network/index.md
  
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: LZHMS/XidianCS
      branch: main
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/LZHMS/XidianCS
    - icon: fontawesome/solid/paper-plane
      link: mailto:zhihaoli2003@outlook.com
    - icon: fontawesome/brands/mastodon
      link: https://lzhms.github.io/    


extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css